index:
  path: /
  defaults: { _controller: 'App\Controller\PublicController::index'}
trick:
  path: /trick/{slug}
  defaults: { _controller: 'App\Controller\PublicController::oneTrick'}
add_trick:
  path: /add-trick
  defaults: { _controller: 'App\Controller\PublicController::addTrick'}
load_more_comment:
  path: /load-more-comment/{id}/{page}
  defaults: {_controller: 'App\Controller\PublicController::loadlistComment', page: 1}
load_more_trick:
  path: /load-more-trick/{page}
  defaults: {_controller: 'App\Controller\PublicController::loadListTrick', page: 1}
remove_trick:
  path: /remove-trick/{id}
  defaults: {_controller: 'App\Controller\PublicController::removeTrick'}
security_login:
  path: /login
  defaults: { _controller: 'App\Controller\UserController::login'}
security_logout:
  path: /logout
  defaults: { _controller: 'App\Controller\UserController::logout'}
register:
  path: /register
  defaults: {_controller: 'App\Controller\UserController::register'}
register_confirm:
  path: /register_confirm
  defaults: {_controller: 'App\Controller\UserController::registerConfirm'}
confirm_user:
  path: /confirm_user/{token}
  defaults: {_controller: 'App\Controller\UserController::confirmUser'}
forgot_password:
  path: /forgot_password
  defaults: {_controller: 'App\Controller\UserController::forgotPassword'}
forgot_password_confirm:
  path: /forgot_password_confirm
  defaults: {_controller: 'App\Controller\UserController::forgotPasswordConfirm'}
reset_password:
  path: /reset_password/{token}
  defaults: {_controller: 'App\Controller\UserController::resetPassword'}
reset_password_confirm:
  path: /reset_password_confirm
  defaults: {_controller: 'App\Controller\UserController::resetPasswordConfirm'}